### ISSUE TITLE
结合conda虚拟环境的实践（或者说官方readme的补充）

### ISSUE THREAD

**Issue by luowuyao** [NewComer00/chinese-pdf-ocr#4]
由于这是两年前的项目，使用的包等都比较老，所以推荐用conda虚拟环境结合老版本的python进行实践。
conda create -n ocr python=3.8#创建一个python=3.8的名字为ocr的虚拟环境
conda activate ocr#进入该虚拟环境

可以按照官方readme进行装包等操作了。
值得一提的是，demo_web有点小bug，请手动将demo_web/目录下的werkzeug更换为2.0.0版本

conda deactivate#退出该虚拟环境
conda remove -n ocr --all#删除该虚拟环境

**Comment by NewComer00** [comment]
感谢您对本项目的支持！这个项目比较老，有人提了PR #3 ，我做了一些修改，正在等待他的回复。
最近我会对项目的依赖等问题进行修复，再次感谢您的支持！

**Comment by luowuyao** [comment]
👍

**Comment by luowuyao** [comment]
作者有空能否在demo_gui加个参数，不弹出页图窗口，仅将页码范围内的所有ocr内容全部打印？
\>ocr.txt时，一个一个关掉窗口还是有点麻烦:D

**Comment by NewComer00** [comment]
> 由于这是两年前的项目，使用的包等都比较老，所以推荐用conda虚拟环境结合老版本的python进行实践。 conda create -n ocr python=3.8#创建一个python=3.8的名字为ocr的虚拟环境 conda activate ocr#进入该虚拟环境
> 
> 可以按照官方readme进行装包等操作了。 值得一提的是，demo_web有点小bug，请手动将demo_web/目录下的werkzeug更换为2.0.0版本
> 
> conda deactivate#退出该虚拟环境 conda remove -n ocr --all#删除该虚拟环境

新的提交 60d75fcd4adb07c8e4bc2a3b088049d822f1b643 更新了依赖的版本

**Comment by NewComer00** [comment]
> 作者有空能否在demo_gui加个参数，不弹出页图窗口，仅将页码范围内的所有ocr内容全部打印？ >ocr.txt时，一个一个关掉窗口还是有点麻烦:D

新的提交 d9af4ff2897d9fa9b5965ff116e9a9bf4dcf8f0a 增加了`--text-only`选项，仅打印识别结果，不展示图片

**Comment by luowuyao** [comment]
感谢
